### ISSUE TITLE
Is it necesary to have custom list of currency names?

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_bitcoin#2]
Moodle already provides `lang/en/currencies.php` that may be already localised. From own experience I can confirm it is extremely annoying to translate such list. What is the point of having same strings in your plugin's language pack?

If bitcoin supports just a subset of what is provided by Moodle, it is better to have an explicit whitelist of currency codes. But forcing Moodle translators to localise currencies again is not a good idea.

**Comment by parthajeet** [comment]
We have updated the code using subset currency only for those not provided by Moodle but required for Bitcoin.

**Comment by mudrd8mz** [comment]
Why are you leaving this issue still open then?

**Comment by parthajeet** [comment]
Okay we are closing the issue now.
