### ISSUE TITLE
Direct access to superglobals

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_bitcoin#3]
I don't think it is necessary to access superglobals such as `$_GET` or even `$_SESSION` directly as you do. Moodle provides wrappers for accessing these that add additional protection layers.

**Comment by parthajeet** [comment]
Direct access to $_GET & $_SESSION has been removed, we are using optional_param() and clean_param_array() instead.

**Comment by mudrd8mz** [comment]
Thanks, it would help to close such resolved issue then.
