### ISSUE TITLE
HTTP header injection vulnerability

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_bitcoin#4]
The file oauth.php is vulnerable to HTTP header injection attack. The attacker could use it to set additional headers, cookies etc.

**Comment by mudrd8mz** [comment]
I am aware of the fact that recent PHP versions added some protection against headers injection. Still, code like this smells :-)

**Comment by parthajeet** [comment]
Hello David,

Now we are fetching param code by using optional_param('code', null, PARAM_RAW);
Also we put some checking as strip_tags(), filter_var() for better security.

Regards,
parthaJeet~

**Comment by mudrd8mz** [comment]
Thanks. You may want to add FILTER_FLAG_STRIP_LOW too.However, as said, recent PHP versions should handle HTTP headers injection themselves. The best thing in this cases is to know the expected $code format and validate it directly via regex or so. Anyway, this looks better now.
