### ISSUE TITLE
What is the point of GLOBAL $SESSION, $CFG in global scripts?

### ISSUE THREAD

**Issue by mudrd8mz** [dualcube/moodle-enrol_bitcoin#6]

**Comment by parthajeet** [comment]
Removed $CFG but global $SESSION is still required and hence present.

**Comment by mudrd8mz** [comment]
Why is `global $SESSION` needed? If I read it correctly, these are global context scripts accesses directly by the browser, not included by another script. Or am i missing something?

**Comment by parthajeet** [comment]
Yes exactly these are global script and should be accessed directly by the browser. But in this page "https://github.com/dualcube/moodle-enrol_bitcoin/blob/master/enrolment_form.php"  if we are not defining global $SESSION; then the session is not accessible.

**Comment by mudrd8mz** [comment]
Indeed. I was referring to places like https://github.com/dualcube/moodle-enrol_bitcoin/blob/master/ipn.php#L38

**Comment by parthajeet** [comment]
Okay, sure we will remove from this page.

Thanks,
parthaJeet~
