### ISSUE TITLE
Feature Request: Support for not using Coinbase

### ISSUE THREAD

**Issue by Geremia** [dualcube/moodle-enrol_bitcoin#7]
Must I use Coinbase to use this plugin, or does it support Bitcoin directly, without any intermediary?
I would like to accept bitcoin directly, without having to sign-up with Coinbase.

There do seem to be some alternatives like [GoUrl.io](https://gourl.io/) ([GoUrl.io on GitHub](https://github.com/cryptoapi/Payment-Gateway)), mentioned on [this Bitcoin Wiki page](https://en.bitcoin.it/wiki/Gourl). It is a "Bitcoin Payment processor with [ready to use php scripts](https://gourl.io/bitcoin-payment-gateway-api.html)."

**Comment by parthajeet** [comment]
Hello,

Coinbase is required to use this plugin.

Regards,
Parthajeet~

**Comment by Geremia** [comment]
@parthajeet Have you considered using the better, open-source pay-processor [BTCPay Server](https://btcpayserver.org/) instead?
